name: Backend pull-request

on:
  pull_request:
    paths:
      - 'backend/**'
      - 'shared/**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install
      - run: yarn workspace @crud/backend test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install
      - run: yarn backend:lint
      - run: yarn workspace @crud/components build
      - run: yarn workspace @crud/backend build
