name: Backend pull-request

on:
  pull_request:
    paths:
      - 'backend/**'
      - 'shared/**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
      - run: yarn workspace @crud/backend test

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          working-directory: backend
          start: yarn workspace @crud/components build, yarn start
          wait-on: 'http://localhost:4000'
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: backend-cypress-videos
          path: backend/cypress/videos

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
      - run: yarn backend:lint
      - run: yarn workspace @crud/components build
      - run: yarn workspace @crud/backend build
